all:
	@echo "There are separate Makefiles in uppgift1 and uppgift2."
	@echo
	@echo "Please use 'make handin' in this directory when you"
	@echo "are ready to submit your work."

handin:
	@echo "Handing in: uppgift1/count.c uppgift2/List.java"
	@echo "Note the files above -- those are the only ones added to the hand-in!"
	@/it/sw/misc/bin/twhandin
