all:
	@echo "There is a separate Makefile in uppgift1."
	@echo
	@echo "Please use 'make handin' in this directory when you"
	@echo "are ready to submit your work."

handin:
	@echo "Handing in: uppgift1/kalloc.c "
	@echo "Note the file(s) above -- those are the only ones added to the hand-in!"
	@/it/sw/misc/bin/twhandin
