test:
	javac -d . *.java
	@echo "Test 1 ================================================="
	@java -cp . org.ioopm.planner.TripPlanner org.ioopm.planner.PrinsEugen
	@echo "Test 2 ================================================="
	@java -cp . org.ioopm.planner.TripPlanner org.ioopm.planner.PrinsEugenByBike

clean:
	rm -rf *.class org
